# Generated by Django 5.2.4 on 2025-09-02 06:40
import sys

from django.db import migrations
from django.conf import settings

DATA = [
    {
        "name": "Tomato",
        "sideline": "#D50000",
        "background": "#F28B82",
        "is_default": True
    },
    {
        "name": "Tangerine",
        "sideline": "#E67C00",
        "background": "#FBBC04",
        "is_default": False
    },
    {
        "name": "Banana",
        "sideline": "#F9AB00",
        "background": "#FFF475",
        "is_default": False
    },
    {
        "name": "Basil",
        "sideline": "#188038",
        "background": "#CCFF90",
        "is_default": False
    },
    {
        "name": "Sage",
        "sideline": "#0B8043",
        "background": "#A7FFEB",
        "is_default": False
    },
    {
        "name": "Peacock",
        "sideline": "#039BE5",
        "background": "#CBF0F8",
        "is_default": False
    },
    {
        "name": "Blueberry",
        "sideline": "#3F51B5",
        "background": "#AECBFA",
        "is_default": False
    },
    {
        "name": "Lavender",
        "sideline": "#8E24AA",
        "background": "#D7AEFB",
        "is_default": False
    },
    {
        "name": "Grape",
        "sideline": "#9C27B0",
        "background": "#FDCFE8",
        "is_default": False
    },
    {
        "name": "Flamingo",
        "sideline": "#C2185B",
        "background": "#F48FB1",
        "is_default": False
    },
    {
        "name": "Graphite",
        "sideline": "#616161",
        "background": "#E0E0E0",
        "is_default": False
    },
    {
        "name": "Pumpkin",
        "sideline": "#E65100",
        "background": "#FFD180",
        "is_default": False
    },
    {
        "name": "Cobalt",
        "sideline": "#1A73E8",
        "background": "#D2E3FC",
        "is_default": False
    },
    {
        "name": "Moss",
        "sideline": "#2E7D32",
        "background": "#E6EE9C",
        "is_default": False
    },
    {
        "name": "Mint",
        "sideline": "#00ACC1",
        "background": "#B2EBF2",
        "is_default": False
    },
    {
        "name": "Steel",
        "sideline": "#546E7A",
        "background": "#CFD8DC",
        "is_default": False
    }
]


def load_default_employee_colors(apps, schema):
    if settings.TEST or 'test' in sys.argv:
        return

    EmployeeColors = apps.get_model('Colors', 'EmployeeColors')
    EmployeeColors.objects.bulk_create([EmployeeColors(**item) for item in DATA])


class Migration(migrations.Migration):
    dependencies = [
        ('Colors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_default_employee_colors)
    ]
