# Generated by Django 5.2.4 on 2025-09-02 07:02
import json
import sys

from django.db import migrations
from django.conf import settings


def load_currencies(apps, scheme_editor):
    if settings.TEST or 'test' in sys.argv:
        return

    Currency = apps.get_model('Currency', 'Currency')
    data = json.load(open('core/Currency/fixtures/currencies_2sep2025.json', 'r'))
    Currency.objects.bulk_create([
        Currency(
            code=item['code'],
            name=item['name'],
            symbol=item['symbol_native'],
        ) for item in data
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('Currency', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_currencies)
    ]
