# Generated by Django 5.2.4 on 2025-08-25 07:08
import json
import sys

from django.db import migrations
from django.conf import settings


def load_countries(apps, scheme_editor):
    if settings.TEST or 'test' in sys.argv:
        return

    Country = apps.get_model('Country', 'Country')
    data = json.load(open('core/Country/fixtures/countries_25aug2025.json', 'r'))
    Country.objects.bulk_create([
        Country(
            name=item['name']['common'],
            cca2=item['cca2'],
            ccn3=item['ccn3'],
        ) for item in data
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('Country', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_countries)
    ]
