# Generated by Django 5.2.4 on 2025-08-26 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(null=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('source', models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov')], default='manually_created', max_length=64)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allergy_cause',
            },
        ),
        migrations.CreateModel(
            name='AllergyReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(null=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('source', models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov')], default='manually_created', max_length=64)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allergy_reaction',
            },
        ),
        migrations.CreateModel(
            name='AllergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(null=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('source', models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov')], default='manually_created', max_length=64)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allergy_type',
            },
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(null=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('source', models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov')], default='manually_created', max_length=64)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'icd_10',
            },
        ),
        migrations.CreateModel(
            name='PatientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(null=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_relation',
            },
        ),
    ]
