# Generated by Django 5.2.4 on 2025-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergycause',
            name='source',
            field=models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov'), ('hl7', 'HL7')], default='manually_created', max_length=64),
        ),
        migrations.AlterField(
            model_name='allergyreaction',
            name='source',
            field=models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov'), ('hl7', 'HL7')], default='manually_created', max_length=64),
        ),
        migrations.AlterField(
            model_name='allergytype',
            name='source',
            field=models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov'), ('hl7', 'HL7')], default='manually_created', max_length=64),
        ),
        migrations.AlterField(
            model_name='icd10',
            name='source',
            field=models.CharField(choices=[('manually_created', 'Manually created'), ('other', 'Other'), ('cms.gov', 'CMS.gov'), ('hl7', 'HL7')], default='manually_created', max_length=64),
        ),
    ]
