# Generated by Django 5.2.4 on 2025-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_alter_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergycause',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='allergycause',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
