# Generated by Django 5.2.4 on 2025-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0003_alter_allergycause_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergytype',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='allergytype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
