# Generated by Django 5.2.4 on 2025-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0004_alter_allergytype_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergyreaction',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='allergyreaction',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
