# Generated by Django 5.2.4 on 2025-08-29 07:55

from django.db import migrations


def load_patient_relations(apps, schema_editor):
    PatientRelation = apps.get_model('Medicine', 'PatientRelation')
    relations = [
        'Mother',
        'Father',
        'Brother',
        'Sister',
        'Spouse',
        'Child',
        'Grandparent',
        'Grandchild',
        'Relative (other)',
        'Caregiver',
    ]
    PatientRelation.objects.bulk_create([PatientRelation(name=name) for name in relations])


class Migration(migrations.Migration):
    dependencies = [
        ('Medicine', '0005_alter_allergyreaction_fields'),
    ]

    operations = [
        migrations.RunPython(load_patient_relations)
    ]
