# Generated by Django 5.2.4 on 2025-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0006_load_patient_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='icd10',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
