# Generated by Django 5.2.4 on 2025-08-17 16:34

import sys
from django.db import migrations
from django.utils import timezone
from django.conf import settings
from zoneinfo import available_timezones, ZoneInfo


def import_timezones(apps, schema_editor):
    if settings.TEST or 'test' in sys.argv:
        return

    TimezoneHandbook = apps.get_model("Timezones", "TimezoneHandbook")
    TimezoneHandbook.objects.all().delete()

    batch = list()
    batch_size = 100
    for i, tz_name in enumerate(available_timezones(), start=0):
        dt = timezone.now().astimezone(ZoneInfo(tz_name))
        offset_td = dt.utcoffset()
        hours, minutes = divmod(offset_td.total_seconds() // 60, 60)
        sign = '+' if hours >= 0 else '-'
        offset = f"{sign}{abs(int(hours)):02d}:{int(minutes):02d}"

        batch.append(TimezoneHandbook(
            name=tz_name,
            offset=offset,
            label=tz_name.replace('_', ' '),
        ))

        if i % batch_size == 0:
            TimezoneHandbook.objects.bulk_create(batch)
            batch = list()

    if batch:
        TimezoneHandbook.objects.bulk_create(batch)

    print(f'\n\t[+] Created {TimezoneHandbook.objects.count()} timezones using zoneinfo')


class Migration(migrations.Migration):
    dependencies = [
        ('Timezones', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_timezones)
    ]
