# Generated by Django 5.2.4 on 2025-09-09 19:14

from django.db import migrations

SLUGS = [
    ('admin', 'Admin'),
    ('doctor', 'Doctor'),
    ('owner', 'Owner'),
]


def load_default_employee_roles(apps, schema):
    EmployeeRole = apps.get_model('Employee', 'EmployeeRole')
    EmployeeRole.objects.bulk_create([EmployeeRole(slug=slug, name=name) for slug, name in SLUGS])


class Migration(migrations.Migration):
    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_default_employee_roles)
    ]
