# Generated by Django 5.2.4 on 2025-09-09 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookUpdateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(null=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('handbook', models.CharField(choices=[('allergy_type', 'Allergy type'), ('allergy_cause', 'Allergy cause'), ('allergy_reaction', 'Allergy reaction'), ('icd_10', 'Icd 10'), ('timezone_handbook', 'Timezone handbook'), ('currency', 'Currency'), ('countries', 'Countries'), ('employee_color', 'Employee color'), ('clinic_pre_settings', 'Clinic pre settings')], max_length=64)),
                ('stamp', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handbook_update_log',
                'indexes': [models.Index(fields=['handbook', 'stamp'], name='handbook_up_handboo_3cab55_idx')],
            },
        ),
    ]
