# Generated by Django 5.2.4 on 2025-09-03 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Country', '0002_load_countries'),
        ('Currency', '0003_alter_currency_code'),
        ('Timezones', '0002_load_timezones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(null=True)),
                ('archived_stamp', models.DateTimeField(null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Country.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currencies', models.ManyToManyField(related_name='currencies', to='Currency.currency')),
                ('primary_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_currency', to='Currency.currency')),
                ('primary_timezone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_timezone', to='Timezones.timezonehandbook')),
                ('timezones', models.ManyToManyField(related_name='timezones', to='Timezones.timezonehandbook')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': ' clinic_pre_settings',
            },
        ),
    ]
