name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432

    env:
      SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: test_settings

      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install env
        run: |
          pip install uv
          uv pip install --system -r requirements.lock

      - name: Wait for DB
        run: |
          for i in {1..10}; do
            pg_isready -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER && break
            sleep 3
          done

      - name: Run code check
        run: |
          python manage.py check
          flake8

      - name: Run migrations
        run: uv run python manage.py migrate --noinput

      - name: Run Tests
        run: uv run python manage.py test
