name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    env:
      UV_PYTHON: ${{ matrix.python-version }}
      SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: test_settings

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run code check
        run: |
          python manage.py check
          flake8
